<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('listing_ab_tests', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('ad_id');
            $table->string('test_name');
            $table->string('test_description')->nullable();
            $table->json('variant_a_config'); // Configuration for variant A (title, description, price, media, etc.)
            $table->json('variant_b_config'); // Configuration for variant B
            $table->timestamp('start_date');
            $table->timestamp('end_date')->nullable();
            $table->string('status')->default('draft'); // draft, running, completed, paused, cancelled
            $table->json('traffic_allocation')->default('{"a": 50, "b": 50}'); // Traffic allocation percentages
            $table->decimal('statistical_significance', 5, 2)->default(95.00); // Statistical significance target (95%)
            $table->string('primary_metric')->default('conversions'); // conversions, clicks, engagement, time_on_page
            $table->json('secondary_metrics')->nullable(); // Additional metrics to track
            $table->string('winner_variant')->nullable(); // 'A', 'B', or 'tie'
            $table->decimal('confidence_level', 5, 2)->default(0.00); // Confidence level in the result
            $table->integer('sample_size_a')->default(0);
            $table->integer('sample_size_b')->default(0);
            $table->decimal('conversion_rate_a', 8, 4)->default(0.0000); // Conversion rate for variant A
            $table->decimal('conversion_rate_b', 8, 4)->default(0.0000); // Conversion rate for variant B
            $table->integer('impression_count_a')->default(0); // Impressions for variant A
            $table->integer('impression_count_b')->default(0); // Impressions for variant B
            $table->integer('click_count_a')->default(0); // Clicks for variant A
            $table->integer('click_count_b')->default(0); // Clicks for variant B
            $table->decimal('engagement_rate_a', 8, 4)->default(0.0000); // Engagement rate for variant A
            $table->decimal('engagement_rate_b', 8, 4)->default(0.0000); // Engagement rate for variant B
            $table->decimal('ctr_a', 8, 4)->default(0.0000); // Click-through rate for variant A
            $table->decimal('ctr_b', 8, 4)->default(0.0000); // Click-through rate for variant B
            $table->decimal('bounce_rate_a', 8, 4)->default(0.0000); // Bounce rate for variant A
            $table->decimal('bounce_rate_b', 8, 4)->default(0.0000); // Bounce rate for variant B
            $table->decimal('time_on_page_a', 8, 2)->default(0.00); // Average time on page for variant A
            $table->decimal('time_on_page_b', 8, 2)->default(0.00); // Average time on page for variant B
            $table->decimal('revenue_a', 15, 2)->default(0.00); // Revenue generated by variant A
            $table->decimal('revenue_b', 15, 2)->default(0.00); // Revenue generated by variant B
            $table->text('notes')->nullable(); // Admin/user notes
            $table->json('custom_fields')->nullable(); // For extended functionality
            $table->timestamps();

            // Indexes
            $table->index('user_id');
            $table->index('ad_id');
            $table->index('status');
            $table->index('primary_metric');
            $table->index(['user_id', 'status']); // For getting user's tests by status
            $table->index(['ad_id', 'status']); // For getting tests for specific ad
            $table->index(['status', 'start_date']); // For admin dashboard
            $table->index('start_date');
            $table->index('end_date');
            $table->index('winner_variant');

            // Foreign key constraints
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('ad_id')->references('id')->on('ads')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('listing_ab_tests');
    }
};
