@extends('layouts.app')

@section('title', ucfirst($reportType) . ' Report')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ route('reports.index') }}">Reports</a></li>
                        <li class="breadcrumb-item active">{{ ucfirst($reportType) . ' Report' }}</li>
                    </ol>
                </div>
                <h4 class="page-title">{{ ucfirst($reportType) . ' Report' }}</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">Report Details</h5>
                        <div>
                            <button type="button" class="btn btn-light btn-sm me-1">
                                <i class="mdi mdi-download"></i> Export PDF
                            </button>
                            <button type="button" class="btn btn-light btn-sm me-1">
                                <i class="mdi mdi-file-excel"></i> Export Excel
                            </button>
                            <button type="button" class="btn btn-primary btn-sm">
                                <i class="mdi mdi-refresh"></i> Regenerate
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <td><strong>Report ID:</strong></td>
                                        <td>{{ $report->id }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Report Type:</strong></td>
                                        <td>{{ ucfirst(str_replace('-', ' ', $reportType)) }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Generated At:</strong></td>
                                        <td>{{ $report->created_at->format('M d, Y H:i:s') }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Period:</strong></td>
                                        <td>{{ $report->period_start->format('M d, Y') }} - {{ $report->period_end->format('M d, Y') }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <td><strong>Generated By:</strong></td>
                                        <td>System</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Report Status:</strong></td>
                                        <td><span class="badge bg-success">Completed</span></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Export Status:</strong></td>
                                        <td><span class="badge bg-secondary">Available</span></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Currency:</strong></td>
                                        <td>USD</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <h5 class="mb-3">Report Data</h5>
                            
                            @if($reportType === 'balance-sheet')
                                <!-- Balance Sheet Specific Content -->
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Assets</h6>
                                                <h3 class="text-success">${{ number_format($report->total_assets, 2) }}</h3>
                                                <p class="text-muted">Total assets including crypto holdings, fiat balances, and escrow funds</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Liabilities</h6>
                                                <h3 class="text-danger">${{ number_format($report->total_liabilities, 2) }}</h3>
                                                <p class="text-muted">User deposits and pending settlements</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Equity</h6>
                                                <h3 class="text-info">${{ number_format($report->total_equity, 2) }}</h3>
                                                <p class="text-muted">Owner's equity and retained earnings</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row mt-4">
                                    <div class="col-md-6">
                                        <h6>Asset Breakdown</h6>
                                        <ul class="list-group">
                                            @foreach($report->assets['crypto_holdings'] ?? [] as $currency => $amount)
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    {{ $currency }} Holdings
                                                    <span class="badge bg-primary rounded-pill">{{ $amount }}</span>
                                                </li>
                                            @endforeach
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Fiat Balances
                                                <span class="badge bg-success rounded-pill">${{ $report->assets['fiat_balances']['USD'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Escrow Funds
                                                <span class="badge bg-info rounded-pill">${{ $report->assets['escrow_funds'] ?? 0 }}</span>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <h6>Liability Breakdown</h6>
                                        <ul class="list-group">
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                User Deposits
                                                <span class="badge bg-danger rounded-pill">${{ $report->liabilities['user_deposits'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Pending Settlements
                                                <span class="badge bg-warning rounded-pill">${{ $report->liabilities['pending_settlements'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Obligations to Users
                                                <span class="badge bg-secondary rounded-pill">${{ $report->liabilities['obligations_to_users'] ?? 0 }}</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                
                            @elseif($reportType === 'income-statement')
                                <!-- Income Statement Specific Content -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Total Revenue</h6>
                                                <h3 class="text-success">${{ number_format($report->total_revenue, 2) }}</h3>
                                                <p class="text-muted">Trading fees, withdrawal fees, etc.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">COGS</h6>
                                                <h3 class="text-danger">${{ number_format($report->total_cost_of_goods_sold, 2) }}</h3>
                                                <p class="text-muted">Payment processing, blockchain fees</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Gross Profit</h6>
                                                <h3 class="text-info">${{ number_format($report->gross_profit, 2) }}</h3>
                                                <p class="text-muted">Revenue minus COGS</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Net Income</h6>
                                                <h3 class="text-warning">${{ number_format($report->net_income, 2) }}</h3>
                                                <p class="text-muted">Final profit after expenses</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row mt-4">
                                    <div class="col-md-6">
                                        <h6>Revenue Breakdown</h6>
                                        <ul class="list-group">
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Trading Fees
                                                <span class="badge bg-success rounded-pill">${{ $report->revenue['trading_fees'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Withdrawal Fees
                                                <span class="badge bg-success rounded-pill">${{ $report->revenue['withdrawal_fees'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Deposit Fees
                                                <span class="badge bg-success rounded-pill">${{ $report->revenue['deposit_fees'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Premium Service Revenue
                                                <span class="badge bg-success rounded-pill">${{ $report->revenue['premium_service_revenue'] ?? 0 }}</span>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <h6>Expense Breakdown</h6>
                                        <ul class="list-group">
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Personnel Costs
                                                <span class="badge bg-danger rounded-pill">${{ $report->operating_expenses['personnel_costs'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Infrastructure Costs
                                                <span class="badge bg-danger rounded-pill">${{ $report->operating_expenses['infrastructure_costs'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Marketing Costs
                                                <span class="badge bg-danger rounded-pill">${{ $report->operating_expenses['marketing_costs'] ?? 0 }}</span>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                Compliance Costs
                                                <span class="badge bg-danger rounded-pill">${{ $report->operating_expenses['compliance_costs'] ?? 0 }}</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                
                            @elseif($reportType === 'cash-flow')
                                <!-- Cash Flow Specific Content -->
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Operating Cash Flow</h6>
                                                <h3 class="text-success">${{ number_format($report->net_operating_cash_flow, 2) }}</h3>
                                                <p class="text-muted">From daily trading activities</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Investing Cash Flow</h6>
                                                <h3 class="text-danger">${{ number_format($report->net_investing_cash_flow, 2) }}</h3>
                                                <p class="text-muted">Infrastructure investments</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Free Cash Flow</h6>
                                                <h3 class="text-info">${{ number_format($report->net_free_cash_flow, 2) }}</h3>
                                                <p class="text-muted">Available after expenses</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row mt-4">
                                    <div class="col-md-12">
                                        <h6>Cash Flow Breakdown</h6>
                                        <div class="table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Description</th>
                                                        <th>Amount</th>
                                                        <th>Date</th>
                                                        <th>Category</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($report->operating_cash_flow as $item)
                                                        <tr>
                                                            <td>{{ $item['description'] }}</td>
                                                            <td>${{ number_format($item['amount'], 2) }}</td>
                                                            <td>{{ $item['date'] }}</td>
                                                            <td><span class="badge bg-success">Operating</span></td>
                                                        </tr>
                                                    @endforeach
                                                    @foreach($report->investing_cash_flow as $item)
                                                        <tr>
                                                            <td>{{ $item['description'] }}</td>
                                                            <td>${{ number_format($item['amount'], 2) }}</td>
                                                            <td>{{ $item['date'] }}</td>
                                                            <td><span class="badge bg-warning">Investing</span></td>
                                                        </tr>
                                                    @endforeach
                                                    @foreach($report->financing_cash_flow as $item)
                                                        <tr>
                                                            <td>{{ $item['description'] }}</td>
                                                            <td>${{ number_format($item['amount'], 2) }}</td>
                                                            <td>{{ $item['date'] }}</td>
                                                            <td><span class="badge bg-info">Financing</span></td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                            @elseif($reportType === 'daily-trading')
                                <!-- Daily Trading Specific Content -->
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Total Volume</h6>
                                                <h3 class="text-success">{{ number_format($report->total_volume, 2) }}</h3>
                                                <p class="text-muted">Trading volume for the day</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Total Transactions</h6>
                                                <h3 class="text-info">{{ $report->total_transactions }}</h3>
                                                <p class="text-muted">Number of trades completed</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Total Fees</h6>
                                                <h3 class="text-warning">${{ number_format($report->total_fees, 2) }}</h3>
                                                <p class="text-muted">Commission revenue</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="card text-center">
                                            <div class="card-body">
                                                <h6 class="text-uppercase">Date</h6>
                                                <h3 class="text-muted">{{ $report->date->format('M d, Y') }}</h3>
                                                <p class="text-muted">Report date</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row mt-4">
                                    <div class="col-md-6">
                                        <h6>Volume by Pair</h6>
                                        <div class="table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Pair</th>
                                                        <th>Volume</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($report->volume_by_pair as $pair => $volume)
                                                        <tr>
                                                            <td>{{ $pair }}</td>
                                                            <td>{{ number_format($volume, 2) }}</td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <h6>Fee Revenue by Pair</h6>
                                        <div class="table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Pair</th>
                                                        <th>Fee Revenue</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($report->fee_revenue['by_pair'] ?? [] as $pair => $revenue)
                                                        <tr>
                                                            <td>{{ $pair }}</td>
                                                            <td>${{ number_format($revenue, 2) }}</td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                            @else
                                <!-- Generic report display -->
                                <div class="alert alert-info">
                                    <h5>Report Data</h5>
                                    <pre class="text-muted" style="max-height: 400px; overflow-y: auto;">{{ json_encode($report->toArray(), JSON_PRETTY_PRINT) }}</pre>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection