<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ListingAbTest extends Model
{
    protected $fillable = [
        'user_id',
        'ad_id',
        'test_name',
        'test_description',
        'variant_a_title',
        'variant_a_description',
        'variant_a_media',
        'variant_a_price',
        'variant_b_title',
        'variant_b_description',
        'variant_b_media',
        'variant_b_price',
        'start_date',
        'end_date',
        'status', // 'running', 'completed', 'paused', 'cancelled'
        'traffic_allocation', // Percentage of traffic to each variant
        'statistical_significance',
        'primary_metric', // 'clicks', 'conversions', 'engagement', 'time_on_page'
        'secondary_metrics', // Additional metrics to track
        'winner_variant', // 'A', 'B', or null if ongoing
        'confidence_level', // Confidence in the result (0-100%)
        'sample_size_a', // Number of samples for variant A
        'sample_size_b', // Number of samples for variant B
        'conversion_rate_a', // Conversion rate for variant A
        'conversion_rate_b', // Conversion rate for variant B
        'impression_count_a', // Number of impressions for variant A
        'impression_count_b', // Number of impressions for variant B
        'click_count_a', // Number of clicks for variant A
        'click_count_b', // Number of clicks for variant B
        'engagement_rate_a', // Engagement rate for variant A
        'engagement_rate_b', // Engagement rate for variant B
        'ctr_a', // Click-through rate for variant A
        'ctr_b', // Click-through rate for variant B
        'bounce_rate_a', // Bounce rate for variant A
        'bounce_rate_b', // Bounce rate for variant B
        'time_on_page_a', // Average time on page for variant A
        'time_on_page_b', // Average time on page for variant B
        'revenue_a', // Revenue generated by variant A
        'revenue_b', // Revenue generated by variant B
        'notes',
        'custom_fields',
    ];

    protected $casts = [
        'variant_a_media' => 'array',
        'variant_b_media' => 'array',
        'traffic_allocation' => 'array',
        'secondary_metrics' => 'array',
        'statistical_significance' => 'decimal:2',
        'conversion_rate_a' => 'decimal:2',
        'conversion_rate_b' => 'decimal:2',
        'engagement_rate_a' => 'decimal:2',
        'engagement_rate_b' => 'decimal:2',
        'ctr_a' => 'decimal:2',
        'ctr_b' => 'decimal:2',
        'bounce_rate_a' => 'decimal:2',
        'bounce_rate_b' => 'decimal:2',
        'time_on_page_a' => 'decimal:2',
        'time_on_page_b' => 'decimal:2',
        'revenue_a' => 'decimal:2',
        'revenue_b' => 'decimal:2',
        'confidence_level' => 'decimal:2',
        'sample_size_a' => 'integer',
        'sample_size_b' => 'integer',
        'impression_count_a' => 'integer',
        'impression_count_b' => 'integer',
        'start_date' => 'date',
        'end_date' => 'date',
        'notes' => 'string',
        'custom_fields' => 'array',
    ];

    /**
     * Get the user who created this test
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the ad this test is for
     */
    public function ad(): BelongsTo
    {
        return $this->belongsTo(Ad::class);
    }

    /**
     * Scope to get tests by status
     */
    public function scopeByStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope to get running tests
     */
    public function scopeRunning($query)
    {
        return $query->where('status', 'running');
    }

    /**
     * Scope to get completed tests
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope to get tests for a specific ad
     */
    public function scopeForAd($query, $adId)
    {
        return $query->where('ad_id', $adId);
    }

    /**
     * Calculate conversion difference between variants
     */
    public function getConversionDifference(): float
    {
        return abs($this->conversion_rate_a - $this->conversion_rate_b);
    }

    /**
     * Calculate lift percentage
     */
    public function getLiftPercentage(): float
    {
        if ($this->conversion_rate_a == 0) return 0;

        return (($this->conversion_rate_b - $this->conversion_rate_a) / $this->conversion_rate_a) * 100;
    }

    /**
     * Check if test has reached statistical significance
     */
    public function hasStatisticalSignificance(): bool
    {
        return $this->statistical_significance >= 95; // 95% confidence level
    }

    /**
     * Determine winner based on primary metric
     */
    public function determineWinner(): string
    {
        if ($this->hasStatisticalSignificance()) {
            if ($this->primary_metric === 'conversions') {
                return $this->conversion_rate_a > $this->conversion_rate_b ? 'A' : 'B';
            } elseif ($this->primary_metric === 'clicks') {
                return $this->click_count_a > $this->click_count_b ? 'A' : 'B';
            } elseif ($this->primary_metric === 'engagement') {
                return $this->engagement_rate_a > $this->engagement_rate_b ? 'A' : 'B';
            } elseif ($this->primary_metric === 'time_on_page') {
                return $this->time_on_page_a > $this->time_on_page_b ? 'A' : 'B';
            }
            // Default to conversion rate if unknown metric
            return $this->conversion_rate_a > $this->conversion_rate_b ? 'A' : 'B';
        }

        return 'indeterminate';
    }

    /**
     * Check if test is currently active
     */
    public function isActive(): bool
    {
        return $this->status === 'running' &&
               now() >= $this->start_date &&
               now() <= $this->end_date;
    }
}
